/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'per' at '2/23/15 5:22 PM' with Gradle 2.2.1
 *
 * @author per, @date 2/23/15 5:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
